### ISSUE TITLE
Use a generator to init an awesome-list

### ISSUE THREAD

**Issue by aloisdg** [alexbooker/awesome-urxvt#1]
Hello,

I know you dislike generator. I will still propose this one. Next time you want to create an awesome-list, you may want to use the [generator awesome list](https://github.com/dar5hak/generator-awesome-list) by @dar5hak. I used it for [awesome-bash](https://github.com/awesome-lists/awesome-bash/). This generator is nicely done! It will allow you to gain a lot of time. There is almost no configuration. I really recommend it. :wink: 

Cheers,

**Comment by alexbooker** [comment]
Oo, I didn't know about that one. Thanks fort the tip :bow:!

**Comment by aloisdg** [comment]
You are welcome. :smile:
